travis:
  secure:
    BINSTAR_TOKEN: juYdEmsiwuB5lG4PH68X+dgywTb60tAoW0cy0cNqOksaIW9+AOKEzwrBSAsy2ohc2f0yM8r1RKWhmRxsplF7HG27s5NPc47eSKbwe1JWVs+6cqfIsQbnRRrTFG8DizQzJ6V6OovCWKobzNoyuCJH2c7njF8BwE/QWP+nZljCKl1fNYZVU65VKX5gxQF3CcQIFUwlO89DJbn5eTBRgu8INQhZ2dpnxTf7ktebbnSLqn2CXvUcpR8B/PoLXOE3QhFFurAwRMxKEyYVlwyFsRgpp/EPRB4roHKE6CSbQDueoiZRn5JyH9M98nges3TirA+UjH45pIVazFxOWxoME7xjhpm7bBjdfRp/P8+NqgQDcVa85UgJPXPNr5Q1kC1Dw7EwlSzB7xkWToDXN2A4e+qVUO6ieK69oBaH6yotlkEOS7ORvVLyr9+asxrux9Jrlyej1zwOsiLaBiRNcY0EEEF4K+ioBYOskeFi147N6a1IA6sEUAud78hSReaqWMe/u4f9mFAgodRPRA+jrAjaguppEEnm720c0iXuQkj0gLBi5gdgemNiyMOnrs8iqsPOOz3YzqtxYdxESU3xWabClABv/2TtKp15GIyS1TQZejIWrbOHtjLD6Ss9w3QaDj0m3JrhBNk7NKbpl3SnIt2hgQ1+O9pEOKLHmgy6jczsrK6d35I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
